global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: fps-tracker
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
          - fps-tracker:5000
    relabel_configs:
      - target_label: instance
        replacement: fps-tracker-app
